## Методичка 1

#### 1. Установить, какие произведения матриц  𝐴𝐵  и  𝐵𝐴  определены, и найти размерности полученных матриц

а) 𝐴 — матрица 4×2, 𝐵 — матрица  4×2  - произведение не определено

б) 𝐴 — матрица  2×5, 𝐵 — матрица  5×3 - произведение определено, размерность результата 2×3

в) 𝐴 — матрица  8×3, 𝐵 — матрица  3×8 - произведение определено, размерность результата 8×8

г) 𝐴 — квадратная матрица 4×4, 𝐵 — квадратная матрица  4×4 - произведение определено, размерность результата 4×4

#### 2. Найти сумму и произведение матриц  A и B

\begin{equation}
A = 
\left({\begin{array}{cc}
1 & -2 \\
3 & 0
\end{array}}\right)
\,
B = 
\left({\begin{array}{cc}
4 & -1 \\
0 & 5
\end{array}}\right)
\end{equation}

\begin{equation}
A + B = 
\left({\begin{array}{cc}
1 & -2 \\
3 & 0
\end{array}}\right)
+
\left({\begin{array}{cc}
4 & -1 \\
0 & 5
\end{array}}\right)
 = 
\left({\begin{array}{cc}
5 & -3 \\
3 & 5
\end{array}}\right)
\end{equation}

\begin{equation}
A \cdot B = 
\left({\begin{array}{cc}
1 & -2 \\
3 & 0
\end{array}}\right)
+
\left({\begin{array}{cc}
4 & -1 \\
0 & 5
\end{array}}\right)
 = 
\left({\begin{array}{cc}
4 & -11 \\
12 & -3
\end{array}}\right)
\end{equation}

In [1]:
import numpy as np

a = np.array([[1, -2],[3, 0]])
b = np.array([[4, -1],[0, 5]])

print('A + B = ', a + b)
print('A * B = ', a.dot(b))

A + B =  [[ 5 -3]
 [ 3  5]]
A * B =  [[  4 -11]
 [ 12  -3]]


#### 3. Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию  3A−2B+4C  для следующих матриц 

\begin{equation}
A = 
\left({\begin{array}{cc}
1 & 7 \\
3 & -6
\end{array}}\right)
\,
B = 
\left({\begin{array}{cc}
0 & 5 \\
2 & 1
\end{array}}\right)
\,
C = 
\left({\begin{array}{cc}
2 & -4 \\
1 & 1
\end{array}}\right)
\end{equation}

\begin{equation}
3A - 2B + 4C = 
3\left({\begin{array}{cc}
1 & 7 \\
3 & -6
\end{array}}\right)
 -
2\left({\begin{array}{cc}
0 & 5 \\
2 & 1
\end{array}}\right)
 +
4\left({\begin{array}{cc}
2 & -4 \\
1 & 1
\end{array}}\right)
 =
\left({\begin{array}{cc}
3 & 21 \\
9 & -18
\end{array}}\right)
 -
\left({\begin{array}{cc}
0 & 10 \\
4 & 2
\end{array}}\right)
 +
\left({\begin{array}{cc}
8 & -16 \\
4 & 4
\end{array}}\right)
 =
\left({\begin{array}{cc}
3 & 11 \\
5 & -20
\end{array}}\right)
 +
\left({\begin{array}{cc}
8 & -16 \\
4 & 4
\end{array}}\right)
 =
\left({\begin{array}{cc}
11 & -5 \\
9 & -16
\end{array}}\right)
\end{equation}

In [3]:
a = np.array([[1, 7],[3, -6]])
b = np.array([[0, 5],[2, 1]])
c = np.array([[2, -4],[1, 1]])

print('3A - 2B + 4C = ', 3*a - 2*b + 4*c)

3A - 2B + 4C =  [[ 11  -5]
 [  9 -16]]


#### 4. Дана матрица  A. Вычислить  $AA^T$  и  $A^TA$ .

\begin{equation}
A = 
\left({\begin{array}{cc}
4 & 1 \\
5 & -2 \\
2 & 3
\end{array}}\right)
\,
A^T = 
\left({\begin{array}{ccc}
4 & 5 & 2 \\
1 & -2 & 3
\end{array}}\right)
\end{equation}

\begin{equation}
A \cdot A^T = 
\left({\begin{array}{cc}
4 & 1 \\
5 & -2 \\
2 & 3
\end{array}}\right)
\cdot
\left({\begin{array}{ccc}
4 & 5 & 2 \\
1 & -2 & 3
\end{array}}\right)
 = 
\left({\begin{array}{ccc}
17 & 18 & 11 \\
18 & 29 & 4 \\
11 & 4 & 13
\end{array}}\right)
\end{equation}

\begin{equation}
A^T \cdot A = 
\left({\begin{array}{ccc}
4 & 5 & 2 \\
1 & -2 & 3
\end{array}}\right)
\cdot
\left({\begin{array}{cc}
4 & 1 \\
5 & -2 \\
2 & 3
\end{array}}\right)
 = 
\left({\begin{array}{cc}
45 & 0 \\
0 & 14
\end{array}}\right)
\end{equation}

In [8]:
a = np.array([[4, 1],[5, -2],[2, 3]])

print('A.T = ', a.T)
print('A * A.T = ', a.dot(a.T))
print('A.T * A = ', a.T.dot(a))

A.T =  [[ 4  5  2]
 [ 1 -2  3]]
A * A.T =  [[17 18 11]
 [18 29  4]
 [11  4 13]]
A.T * A =  [[45  0]
 [ 0 14]]


#### 5*. Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [113]:
def matrix_multy(a, b):
    if len(a[0]) != len(b):
        raise Exception(f'Impossible to multiply matrixes with shapes {len(a[0])} and {len(b)}')
        
    c = []
    for aa in a:
        ct = []
        for i in range(len(b[0])):
            bb = [row[i] for row in b]
            ct.append(sum([ai * bi for ai, bi in zip(aa,bb)]))
        c.append(ct)
    
    return c

In [114]:
a = [[1, -2],[3, 0]]
b = [[4, -1],[0, 5]]

matrix_multy(a, b)

[[4, -11], [12, -3]]

In [115]:
a = [[4, 1],[5, -2],[2, 3]]
b = [[4, 5, 2],[1, -2, 3]]

matrix_multy(a, b)

[[17, 18, 11], [18, 29, 4], [11, 4, 13]]