In [1]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

In [4]:
A = np.array([[1,2,0],[0,0,5],[3,-4,2],[1,6,5],[0,1,0]])
print(f'Матрица A:\n{A}')

Матрица A:
[[ 1  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]]


In [8]:
U, s, W = np.linalg.svd(A)
V = W.T

D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s

In [6]:
print(f'Матрица U:\n{U}')

Матрица U:
[[ 0.17  0.16 -0.53 -0.8  -0.16]
 [ 0.39 -0.53  0.61 -0.43  0.03]
 [-0.14 -0.82 -0.52  0.14  0.07]
 [ 0.89  0.06 -0.25  0.38 -0.06]
 [ 0.08  0.11 -0.08 -0.11  0.98]]


In [7]:
print(f'Матрица V:\n{V}')

Матрица V:
[[ 0.07 -0.37 -0.93]
 [ 0.72  0.67 -0.21]
 [ 0.69 -0.65  0.31]]


In [14]:
print(f'V*V.T =\n{V.dot(V.T)}\n-значит V ортогональная')

V*V.T =
[[ 1. -0. -0.]
 [-0.  1. -0.]
 [-0. -0.  1.]]
-значит V ортогональная


In [9]:
print(f'Матрица D:\n{D}')

Матрица D:
[[8.82 0.   0.  ]
 [0.   6.14 0.  ]
 [0.   0.   2.53]
 [0.   0.   0.  ]
 [0.   0.   0.  ]]


In [17]:
print(f'U*D*V.T =\n{np.dot(U.dot(D), V.T)} = A\n {A}')

U*D*V.T =
[[ 1.  2.  0.]
 [ 0. -0.  5.]
 [ 3. -4.  2.]
 [ 1.  6.  5.]
 [-0.  1.  0.]] = A
 [[ 1  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]]


In [22]:
l2 = np.linalg.norm(A, 2)
print(f'Евклидова норма: {l2}')
print(f'l2 = D[1,1], где {l2} = {D[0,0]}')

Евклидова норма: 8.824868854820444
l2 = D[1,1], где 8.824868854820444 = 8.824868854820442


In [21]:
print(f'Норма Фробениуса: {np.linalg.norm(A, "fro")}')

Норма Фробениуса: 11.045361017187261
